# Generated by Django 3.0.4 on 2020-03-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200315_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=43.6426, max_digits=19),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=79.3871, max_digits=19),
        ),
    ]
