# Generated by Django 3.0.4 on 2020-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200315_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='latitude',
            field=models.CharField(default='43', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='longitude',
            field=models.CharField(default='-79', max_length=25),
        ),
    ]
