# Generated by Django 3.0.4 on 2020-03-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200315_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
