# Generated by Django 3.0.4 on 2020-03-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200315_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default='43', max_digits=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default='-79', max_digits=19),
        ),
    ]
